apiVersion: apps/v1
kind: Deployment
metadata:
  name: minetest-deployment
  labels:
    app: minetest
spec:
  selector:
    matchLabels:
      app: minetest
  template:
    metadata:
      labels:
        app: minetest
    spec:
      containers:
      - name: minetest
        image: docker.io/dievri/minetest:server
        ports:
        - containerPort: 30000
          protocol: UDP
        volumeMounts:
        - name: settings
          mountPath: /root/.minetest/minetest.conf
        - name: mods
          mountPath: /usr/share/games/minetest/games/minetest_game/mods
      volumes:
        - name: settings
          hostPath:
            path: /etc/minetest/minetest.conf
            type: File
        - name: mods
          hostPath:
            path: /usr/share/games/minetest/games/minetest_game/mods
            type: Directory

