version: "3"
services:
    server:
        build: . 
        ports:
            - "30000:30000/udp"
        volumes:
            - "/usr/share/games/minetest/games/minetest_game/mods:/usr/share/games/minetest/games/minetest_game/mods"
            - "/etc/minetest/minetest.conf:/root/.minetest/minetest.conf"
        command: ["--port", "30000"]
