version: "3"
services:
    server:
        build: . 
        ports:
            - "30000:30000/udp"
        volumes:
            - "/usr/share/games/minetest/games/minetest_game/mods:/usr/share/games/minetest/games/minetest_game/mods"
            - "/etc/minetest/minetest.conf:/root/.minetest/minetest.conf"
        command: ["--port", "30000"]
    inferno:
        image: "dievri/inferno-os:latest"
        ports:
            - "1916:1916"
        volumes:
            - "~/cdmod/profile:/usr/inferno-os/lib/sh/profile"
