version: "3"
services:
    server:
        build: . 
        ports:
            - "30000:30000/udp"
        volumes:
            - "~/.minetest/mods:/root/.minetest/mods"
        command: ["--worldname", "cdworld", "--port", "30000"]
