apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2020-09-09T11:24:11Z"
    labels:
      component: apiserver
      provider: kubernetes
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:component: {}
            f:provider: {}
        f:spec:
          f:clusterIP: {}
          f:ports:
            .: {}
            k:{"port":443,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: kube-apiserver
      operation: Update
      time: "2020-09-09T11:24:11Z"
    name: kubernetes
    namespace: default
    resourceVersion: "157"
    selfLink: /api/v1/namespaces/default/services/kubernetes
    uid: 432a8a17-d7ea-44b3-8081-a107a522565a
  spec:
    clusterIP: 10.96.0.1
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"minetest-client","namespace":"default"},"spec":{"ports":[{"name":"minetest-server","nodePort":30800,"port":30000,"protocol":"UDP","targetPort":30000},{"name":"inferno","port":1916,"protocol":"TCP","targetPort":1916}],"selector":{"app":"minetest-game"},"sessionAffinity":"None","type":"NodePort"},"status":{"loadBalancer":{}}}
    creationTimestamp: "2020-09-09T16:14:56Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          f:externalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":1916,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":30000,"protocol":"UDP"}:
              .: {}
              f:name: {}
              f:nodePort: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector:
            .: {}
            f:app: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2020-09-09T16:14:56Z"
    name: minetest-client
    namespace: default
    resourceVersion: "13883"
    selfLink: /api/v1/namespaces/default/services/minetest-client
    uid: 3a1cce98-8bfb-47c0-bef1-a158ce67bccc
  spec:
    clusterIP: 10.98.54.70
    externalTrafficPolicy: Cluster
    ports:
    - name: minetest-server
      nodePort: 30800
      port: 30000
      protocol: UDP
      targetPort: 30000
    - name: inferno
      nodePort: 30165
      port: 1916
      protocol: TCP
      targetPort: 1916
    selector:
      app: minetest-game
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2020-09-09T16:29:04Z"
    labels:
      app: minetest-game
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app: {}
        f:spec:
          f:ports:
            .: {}
            k:{"port":1916,"protocol":"TCP"}:
              .: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector:
            .: {}
            f:app: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: kubectl-expose
      operation: Update
      time: "2020-09-09T16:29:04Z"
    name: minetest-inferno
    namespace: default
    resourceVersion: "14602"
    selfLink: /api/v1/namespaces/default/services/minetest-inferno
    uid: fe0d2058-e6ff-4860-beb2-920d1b37b838
  spec:
    clusterIP: 10.103.124.133
    ports:
    - port: 1916
      protocol: TCP
      targetPort: 1916
    selector:
      app: minetest-game
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
