apiVersion: v1
kind: Service
metadata:
  labels:
    app: minetest
  name: minetest-deployment
  namespace: default
spec:
  ports:
    - nodePort: 30800
      port: 30000
      protocol: UDP
      targetPort: 30000
  selector:
    app: minetest
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minetest-deployment
  labels:
    app: minetest
spec:
  selector:
    matchLabels:
      app: minetest
  template:
    metadata:
      labels:
        app: minetest
    spec:
      containers:
        - name: minetest
          image: docker.io/dievri/minetest:server
          ports:
            - containerPort: 30000
              protocol: UDP
          volumeMounts:
            - name: settings
              mountPath: /root/.minetest/minetest.conf
            - name: mods
              mountPath: /usr/share/games/minetest/games/minetest_game/mods

        - name: inferno
          image: dievri/inferno-os:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1916
              protocol: TCP
          volumeMounts:
            - name: profile
              mountPath: /usr/inferno-os/lib/sh/profile
      volumes:
        - name: profile
          hostPath:
                path: /data/profile
                type: File
        - name: settings
          hostPath:
                path: /data/minetest.conf
                type: File
        - name: mods
          hostPath:
                path: /mods
                type: Directory
