apiVersion: v1
kind: Service
metadata:
  labels:
    app: minetest
  name: minetest-deployment
  namespace: default
spec:
  ports:
  - nodePort: 30800
    port: 30000
    protocol: UDP
    targetPort: 30000
  selector:
    app: minetest
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
